# Setting
gpus: 
seed: 1
debug: False
pretrained_path: /workspace/pretrained_models
work_dir: /workspace/workdir
no_progress_bar: False

# Visualization
visualization_class: 0
visualization_sample: 0
visualization_frames: []

# Data Loader
# mediapipe61-xsub, mediapipe61, mediapipe61-xsub120, mediapipe61-xset120
dataset: mediapipe61-xsub120
dataset_args:
  mediapipe61:
    train_batch_size: 32
    eval_batch_size: 32
    num_frame: 288
    inputs: JVB
    transform: False
    root_folder: /workspace/npy_converted_full_v3
    ntu60_path: ./data/raw_skeleton/nturgbd_skeletons_s001_to_s017
    ntu120_path: ./data/raw_skeleton/nturgbd_skeletons_s018_to_s032

# Model
model_type: EfficientGCN-B0
model_args:
  stem_channel: 64
  block_args: [[48,1,0.5],[24,1,0.5],[64,2,1],[128,2,1]]
  fusion_stage: 2
  act_type: swish
  att_type: stja
  layer_type: Sep
  drop_prob: 0.25
  kernel_size: [5,2]
  scale_args: [1.2,1.35]
  expand_ratio: 2
  reduct_ratio: 4
  bias: True
  edge: True

# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
  Adam:
    lr: 0.1
    betas: [0.9,0.99]
    weight_decay: 0.0001

# Scheduler
# step, cosine
lr_scheduler: cosine
scheduler_args:
  step:
    max_epoch: 70
    warm_up: 10
    step_lr: [20,50]
  cosine:
    max_epoch: 70
    warm_up: 10
